In [1]:
# 以下兩行是畫圖用
%matplotlib inline
import matplotlib.pyplot as plt
# 載入pandas套件
import pandas as pd
import numpy as np

In [2]:
# 01
scores = {'Math':[90,50,70,80],
          'English':[60,70,90,50],
          'History':[33,75,88,60]}

df = pd.DataFrame(scores)
df

Math  English  History
0    90       60       33
1    50       70       75
2    70       90       88
3    80       50       60

In [3]:
# 02
df.index = ['Simon','Allen','Jimmy','Peter']
df

Math  English  History
Simon    90       60       33
Allen    50       70       75
Jimmy    70       90       88
Peter    80       50       60

In [4]:
# 03
df.index

Index(['Simon', 'Allen', 'Jimmy', 'Peter'], dtype='object')

In [5]:
# 04
df.columns

Index(['Math', 'English', 'History'], dtype='object')

In [6]:
# 05
df.values

array([[90, 60, 33],
       [50, 70, 75],
       [70, 90, 88],
       [80, 50, 60]])

In [7]:
# 06
df.shape

(4, 3)

In [8]:
# 07
df.dtypes

Math       int64
English    int64
History    int64
dtype: object

In [9]:
# 08
s = pd.Series([1, 2, 3])
print(f's的維度 {s.shape}')
s

s的維度 (3,)


0    1
1    2
2    3
dtype: int64

In [10]:
# 09
d = s.to_frame()
print(f'd的維度 {d.shape}')
d

d的維度 (3, 1)


0
0  1
1  2
2  3

In [11]:
# 10
t = d.T
print(f't的維度 {t.shape}')
t

t的維度 (1, 3)


0  1  2
0  1  2  3

In [12]:
# 11
np_a = np.array([1,2,3])
print(f'np_a的維度 {np_a.shape}')
np_a

np_a的維度 (3,)


array([1, 2, 3])

In [13]:
# 12
np_a2 = np_a.reshape(3,1)
print(f'np_a2的維度 {np_a2.shape}')
np_a2

np_a2的維度 (3, 1)


array([[1],
       [2],
       [3]])

In [14]:
# 13
np_a.reshape(-1,1).shape

(3, 1)

In [15]:
# 14
np_a.reshape(1,-1).shape

(1, 3)

In [16]:
# 15
np.array([[1,2,3]]).shape

(1, 3)

In [17]:
# 16
np_a2.reshape(-1).shape

(3,)

In [18]:
# 17
np_a2.ravel().shape

(3,)

In [20]:
# 18
import numpy as np
np.NaN == np.NaN

False

In [19]:
# 19
pd.isnull(np.NaN)

True

In [21]:
# 20
pd.notnull(np.NaN)

False

In [22]:
# 21
scores = {'Math':[90,50,70,80],
          'English':[60,70,90,50],
          'History':[33,np.nan,np.nan,60]}

df = pd.DataFrame(scores, index=['Simon','Allen','Jimmy','Peter'])
df

Math  English  History
Simon    90       60     33.0
Allen    50       70      NaN
Jimmy    70       90      NaN
Peter    80       50     60.0

In [23]:
# 22
df.isnull()

Math  English  History
Simon  False    False    False
Allen  False    False     True
Jimmy  False    False     True
Peter  False    False    False

In [24]:
# 23
df.isnull().sum()

Math       0
English    0
History    2
dtype: int64

In [25]:
# 24
df.isnull().sum().sum()

2

In [ ]:
# 25
df.isnull().any(axis=1)

In [ ]:
# 26
df[df.isnull().any(axis=1)]